#!/bin/sh

docker run -it \
-p 8888:8888 -p 8081:8081 \
-e LOCALHOST_TARGET=${LOCALHOST_TARGET-"host.docker.interna"} \
soluble/sproxy mitmweb \
-p 8888 --web-iface 0.0.0.0 \
-s /scripts/localhost_rewrite.py \
$@